#!/usr/bin/env bash
# ============================================================
# Perry's Wan 2.2 Pipeline — ComfyUI Setup Script (Bare Metal)
# ============================================================
# Run this ONCE on your machine (or inside Docker during build).
# It clones ComfyUI, installs PyTorch for CUDA 12.6/12.4, and
# installs all confirmed custom node packages.
#
# TESTED ON:
#   GPU    : NVIDIA A100-SXM4-80GB
#   CUDA   : 12.6  (driver 535.183.06)
#   Python : 3.10.x
#   OS     : Ubuntu 22.04
#
# USAGE:
#   chmod +x scripts/setup_comfyui.sh
#   ./scripts/setup_comfyui.sh
# ============================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; NC='\033[0m'; BOLD='\033[1m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }
info() { echo -e "${BLUE}[→]${NC} $*"; }
section() { echo; echo -e "${BOLD}══════════════════════════════════════════════${NC}"; echo -e "${BOLD}  $*${NC}"; echo -e "${BOLD}══════════════════════════════════════════════${NC}"; echo; }

# ── Configuration ─────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
COMFYUI_DIR="${BASE_DIR}/ComfyUI"
COMFYUI_VERSION="v0.3.40"

# ── Pre-flight checks ─────────────────────────────────────────
section "Pre-flight Checks"

# Check Python
python_ver=$(python3 --version 2>&1 | grep -oP '3\.\d+' | head -1)
if [[ -z "$python_ver" ]]; then
    err "Python 3.10+ is required. Install with: sudo apt install python3.10 python3.10-venv python3-pip"
fi
log "Python: $(python3 --version)"

# Check CUDA
if ! command -v nvidia-smi &>/dev/null; then
    err "nvidia-smi not found. NVIDIA drivers must be installed first."
fi
log "NVIDIA Driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)"
log "CUDA Version : $(nvidia-smi | grep -oP 'CUDA Version: \K[\d.]+')"

# Check git
command -v git &>/dev/null || err "git not found. Install with: sudo apt install git"
log "Git: $(git --version)"

# Check disk space (need at least 80 GB)
avail_gb=$(df -BG "${BASE_DIR}" | tail -1 | awk '{print $4}' | tr -d 'G')
if [[ "$avail_gb" -lt 80 ]]; then
    warn "Only ${avail_gb} GB free. Pipeline needs ~80 GB for all models."
    warn "Continue only if models are already downloaded elsewhere."
fi
log "Disk space: ${avail_gb} GB available"

# ── Clone ComfyUI ─────────────────────────────────────────────
section "Cloning ComfyUI (pinned to ${COMFYUI_VERSION})"

if [[ -d "${COMFYUI_DIR}/.git" ]]; then
    warn "ComfyUI directory already exists at ${COMFYUI_DIR}"
    warn "Skipping clone. If you want a fresh install, delete it first."
else
    git clone https://github.com/comfyanonymous/ComfyUI "${COMFYUI_DIR}"
    cd "${COMFYUI_DIR}"
    git checkout "${COMFYUI_VERSION}"
    log "ComfyUI cloned and pinned to ${COMFYUI_VERSION}"
fi

cd "${COMFYUI_DIR}"

# ── Install PyTorch (CUDA 12.4 build — compatible with CUDA 12.6 driver) ─────
section "Installing PyTorch for CUDA 12.4 (compatible with CUDA 12.6 driver)"
info "CUDA 12.6 driver is backward-compatible with CUDA 12.4 PyTorch builds."
info "This is the safest combination for stable A100 performance."

pip install \
    torch==2.5.1+cu124 \
    torchvision==0.20.1+cu124 \
    torchaudio==2.5.1+cu124 \
    --index-url https://download.pytorch.org/whl/cu124

log "PyTorch installed"

# Verify GPU is visible
python3 -c "
import torch
assert torch.cuda.is_available(), 'CUDA not available after PyTorch install!'
print(f'  GPU detected : {torch.cuda.get_device_name(0)}')
print(f'  VRAM total   : {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB')
print(f'  CUDA version : {torch.version.cuda}')
"
log "GPU torch test passed"

# ── Install ComfyUI base requirements ─────────────────────────
section "Installing ComfyUI base requirements"
pip install -r "${COMFYUI_DIR}/requirements.txt"
log "ComfyUI requirements installed"

# ── Install pipeline requirements ─────────────────────────────
section "Installing pipeline requirements"
pip install -r "${BASE_DIR}/requirements.txt"
log "Pipeline requirements installed"

# ── Create model directory structure ──────────────────────────
section "Creating model directories"
mkdir -p \
    "${BASE_DIR}/models/diffusion_models" \
    "${BASE_DIR}/models/vae" \
    "${BASE_DIR}/models/text_encoders" \
    "${BASE_DIR}/models/loras" \
    "${BASE_DIR}/inputs" \
    "${BASE_DIR}/outputs"
log "Model directories created"

# ── Write extra_model_paths.yaml so ComfyUI finds our models ──
section "Writing ComfyUI model paths config"
cat > "${COMFYUI_DIR}/extra_model_paths.yaml" << YAML
# Auto-generated by setup_comfyui.sh
# Tells ComfyUI to look in our pipeline's models/ directory
perry_pipeline:
  base_path: ${BASE_DIR}/models
  diffusion_models: diffusion_models/
  vae: vae/
  text_encoders: text_encoders/
  loras: loras/
  clip: clip/

YAML
log "extra_model_paths.yaml written to ${COMFYUI_DIR}/extra_model_paths.yaml"

# ── Copy workflow files ────────────────────────────────────────
section "Copying workflows"
mkdir -p "${COMFYUI_DIR}/workflows"
if ls "${BASE_DIR}/workflows"/*.json &>/dev/null; then
    cp "${BASE_DIR}/workflows"/*.json "${COMFYUI_DIR}/workflows/"
    log "Workflow files copied to ${COMFYUI_DIR}/workflows/"
else
    warn "No workflow JSON files found in ${BASE_DIR}/workflows/"
    warn "Place the 3 workflow JSON files there and re-run, or copy manually."
fi

# ── Custom Nodes ──────────────────────────────────────────────
section "Installing Custom Nodes"
CN_DIR="${COMFYUI_DIR}/custom_nodes"
mkdir -p "${CN_DIR}"

install_node() {
    local name="$1"
    local url="$2"
    local dir="${CN_DIR}/${name}"

    if [[ -d "${dir}/.git" ]]; then
        log "Already installed: ${name} — pulling latest"
        cd "${dir}" && git pull --quiet && cd "${CN_DIR}"
    else
        info "Cloning: ${name}"
        git clone "${url}" "${dir}"
        log "Installed: ${name}"
    fi

    # Install Python requirements if present
    if [[ -f "${dir}/requirements.txt" ]]; then
        pip install -r "${dir}/requirements.txt" --quiet
        log "Deps installed for: ${name}"
    fi
}

# ── 1. KJNodes (ImageResizeKJv2, DiffusionModelLoaderKJ, GetNode, SetNode)
install_node "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes"

# ── 2. VideoHelperSuite (VHS_VideoCombine, LoadVideo)
install_node "ComfyUI-VideoHelperSuite" "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"

# ── 3. Comfyroll (RegexReplace, PreviewAny)
install_node "ComfyUI_Comfyroll_CustomNodes" "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes"

# ── 4. Ask_Gemini / MasterKey ─────────────────────────────────
echo
echo -e "${YELLOW}══════════════════════════════════════════════${NC}"
echo -e "${YELLOW}  ⚠️  MANUAL STEP REQUIRED: Ask_Gemini / MasterKey${NC}"
echo -e "${YELLOW}══════════════════════════════════════════════${NC}"
echo
echo "  The Ask_Gemini and MasterKey custom nodes are required but their"
echo "  source repository is not publicly confirmed."
echo
echo "  TWO OPTIONS:"
echo
echo "  OPTION A — If you know the git URL (fill in below and uncomment):"
echo "    # install_node \"<folder-name>\" \"https://github.com/<user>/<repo>\""
echo
echo "  OPTION B — Install via ComfyUI Manager after startup:"
echo "    1. Start ComfyUI:  bash scripts/start_comfyui.sh"
echo "    2. Open browser:   http://localhost:8188"
echo "    3. Click Manager → Install Missing Nodes"
echo "    4. Load any workflow JSON — Manager finds the missing package"
echo
echo "  To find the repo from your working machine:"
echo "    grep -r 'class Ask_Gemini\|class MasterKey' ComfyUI/custom_nodes/"
echo "    cd ComfyUI/custom_nodes/<found_folder> && git remote -v"
echo -e "${YELLOW}══════════════════════════════════════════════${NC}"
echo

# ── Final summary ─────────────────────────────────────────────
section "Setup Complete"
log "ComfyUI installed at:  ${COMFYUI_DIR}"
log "Models expected at:    ${BASE_DIR}/models/"
log "Workflows copied to:   ${COMFYUI_DIR}/workflows/"
echo
info "NEXT STEPS:"
echo "  1.  Download models:   python3 scripts/download_models.py"
echo "  2.  Verify setup:      python3 scripts/verify_setup.py"
echo "  3.  Start ComfyUI:     bash scripts/start_comfyui.sh"
echo "  4.  Open browser:      http://localhost:8188"
echo
